name = "homepage"
compatibility_date = "2025-06-28"
main = ".svelte-kit/cloudflare/_worker.js"
[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
[env.production.placement]
mode = "smart"
